### ISSUE TITLE
Pages: Create, Edit, Publish, Archive, Delete

### ISSUE THREAD

**Issue by svenseeberg** [Integreat/cms-django#11]
Add functionality to create, edit, publish, archive and delete a page. Changes to pages have to be versioned.

For editing, there should be a WYSIWYG editor as well as a simple markup language.
The editor should support arabic text direction by default.

Enable minor edits which do not change the translation status.

It must be possible to add media to a page and embed images. See #48 

For API v0/v1/v2 compatibility, the page ID of deleted pages must be tracked. Alternatively, deletion must be disallowed in favor of archiving. See #12 

This page should also list the corresponding feedback.

- [x] Create
- [x] Edit
- [x] Publish
- [x] Archive
- [ ] Delete

**Comment by sascha11110** [comment]
Since some municipalities already use HTML as their markup language, we should stick with it.
