### ISSUE TITLE
Multisite domains

### ISSUE THREAD

**Issue by svenseeberg** [Integreat/cms-django#114]
This issue is about discussing the "multisite" support in our new CMS.

1) We should consider the naming. According to our naming convention we should probably name this "multi region support".

2) During our team call we discussed if this should be implemented with subdomains or as paths (https://[REGION].integreat-app.de/ or https://cms.integreat-app.de/[REGION]/). There is no clear preference yet. However, to implement APIv3 we need support the path option.

3) We discussed to have the API available under https://api.integreat.app. Is this still something we want to have? This would influence the discussion somewhat.

**Comment by timoludwig** [comment]
We have implemented the second approach (`https://cms.integreat-app.de/[REGION]/`) and I don't see an urgent reason to add subdomains as well. If this pops up in the future, we can re-open this issue.
