### ISSUE TITLE
Pages: list of archived pages

### ISSUE THREAD

**Issue by svenseeberg** [Integreat/cms-django#12]
It is necessary to keep a list of of deleted pages pages. It is sufficient to keep the ID in store, but drop the content.

This feature is required for API v0/v1/v2 compatibility. See #11. It is possible that we do not need APIv0 to v2 compatibility. There are very few users left using the old API. We have to evaluate the situation before taking on this issue.

**Comment by sascha11110** [comment]
@svenseeberg I think https://github.com/Integreat/cms-django/pull/129 solved this issue right? What is API compatibility about?

**Comment by svenseeberg** [comment]
The old API versions (0 to 2) rely on the server knowing which pages existed in the past. That means, the server tells the client which pages were removed since last contact between client and server.

The task is only completed, if we do not allow deleting pages. If we have a "delete" option (potentially only for superadmins) we should not remove the page itself, but only the translations, and add a "deleted" page property (or something like that).

**Comment by sascha11110** [comment]
Okay, then I leave the issue open, as we have not decided yet about the deletion process / possibility.

**Comment by svenseeberg** [comment]
We will kill API versions 0, 1, and 2
