### ISSUE TITLE
Research alternatives to drf-yasg

### ISSUE THREAD

**Issue by svenseeberg** [Integreat/cms-django#152]
`drf-yasg` is not available in Debian or Ubuntu packages. Therefore we may want to replace or remove it. Alternatively, we can package it.

**Comment by timoludwig** [comment]
This package is just needed for the django rest framework, right? So if we decide not to use drf, we can also drop drf-yasg.

**Comment by timoludwig** [comment]
Ah, @ulliholtgrave removed the package in 4ddda297ceed3798165becabae1a01e1e809235c, so we can close this issue I think.
