### ISSUE TITLE
Add natural language names

### ISSUE THREAD

**Issue by timoludwig** [Integreat/cms-django#168]
In the language creation form, we also need a form for the native name of the language. Also, we need both the names in German and English to show them in the backend languages.
It should be flexible to be extended with new backend languages.
Probably just add hardcoded language name translation fields to the language model.

**Comment by maxammann** [comment]
I have a feature request which maybe fits to this: It would be cool if the API would deliver a property which tells whether the language is RTL/LTR like here:

https://gist.githubusercontent.com/AdamRamberg/ecf2451505416114048c5f89ad6f028f/raw/5e582dbe586396d6e80a02de4586b9e032945f11/locales.js
