### ISSUE TITLE
IntegrityError in language tree

### ISSUE THREAD

**Issue by florianhofhammer** [Integreat/cms-django#174]
I just found a bug causing an `IntegrityError` in the language tree. The error can be reproduced reliably in the current state of the develop branch.

Steps to reproduce:
- In the network admin view:
  - Create a new region
  - Create at least two languages (in the following steps, we assume the two languages to be German and Englisch, works with any other languages as well)
- In the region view (in the region we just created):
  - Create a new language node for the base language (German in this example)
  - **Bug occurs in the next steps, therefore I provide a more precise description of the following steps:** in the language tree view, click on "create language tree node"
  - Choose "English" as language, "German" as source language, check the checkbox for language activation
  - click on "save", a success message should show up
  - click on "save" again without changing any form fields
  - now the form fields should have the following contents:
    - language: "English"
    - source language: "German"
    - activate language: is checked (`true`)
  - change language field to "German", as all languages can be chosen again
  - now the form fields should have the following contents:
    - language: "German"
    - source language: "German"
    - activate language: is checked (`true`)
  - click on "save" again
  - `IntegrityError` occurs

**Comment by florianhofhammer** [comment]
Using the same approach until the step when changing the language field to "German", I also can select nodes in the language trees of other regions as source language. This doesn't lead to a crash, but shows an error message. Is this the desired behaviour or another bug (probably with the same cause)?

**Comment by timoludwig** [comment]
The restrictions for the language tree node form are currently only present in the get-method, but not in post. This leads to the integrity error if incorrect values are selected after performing a save-request. The error is resolved by redirecting to the get view after a successful post.
