### ISSUE TITLE
Fix developer tools and scripts

### ISSUE THREAD

**Issue by Ponitac** [Integreat/cms-django#180]
As we changed our dev setup, a few of our integreat-cms and scripts aren't working correctly anymore.
Identified problems:

- **dev-tools/migrate.sh**: Only works with bash and not with zsh

- **integreat-cms migrate**: Has no effect and one should use "bash dev-tools/migrate"

-  **dev-tools/create_superuser.sh**: Behaves differently then "integreat-cms createsuperuser"

For problems related to zsh and bash, @timoludwig suggested to add a shebang to all .sh-files.

**Comment by timoludwig** [comment]
One comment on `create_superuser.sh`: I created this script to automatically create a superuser called "root" without e-mail-address. If you want to have the default functionality, just use `integreat-cms createsuperuser` instead.
