### ISSUE TITLE
API: page feedback

### ISSUE THREAD

**Issue by svenseeberg** [Integreat/cms-django#22]
Implement endpoint for posting feedback on a page.

The following definition should be supported: https://github.com/Integreat/cms/wiki/REST-APIv3-Documentation#pageeventdisclaimer

The API should accept an JSON object as defined in the above link, but also HTTP POST variables with the same names.

**Comment by timoludwig** [comment]
This issue is already partly resolved in https://github.com/Integreat/cms-django/blob/develop/src/api/v3/feedback.py.
