### ISSUE TITLE
Fix archiving/restoring of pages

### ISSUE THREAD

**Issue by timoludwig** [Integreat/cms-django#288]
Currently, the restoring mechanism of pages is broken. Pages can only be archived and the restore button has no effect.

**Comment by florianhofhammer** [comment]
For me, not even archiving a page works. Same applies to the deletion of pages.
Trying the same with pois however doesn't yield any problems. As far as I've seen in the template code, they're implemented differently. In the `poi_list_row.html` template, the buttons are implemented with the help of the `data-action` and `data-confirmation-popup` attributes while the button behavior in `page_tree_node.html` relies on the corresponding button's `action` attribute.

**Comment by timoludwig** [comment]
Ah yes, you're right. I only tried to archive a page via the page form (which works) but not via the page tree (which doesn't work).
I improved the confirmation popup structure for pois, so I suggest to adapt this new structure also to pages rather than searching the bug in the existing code.
