### ISSUE TITLE
Events: Create, Edit, Delete

### ISSUE THREAD

**Issue by svenseeberg** [Integreat/cms-django#30]
The creation and editing of events should need different privileges than editing pages.

We do not want to version events.

An event should contain (completeness needs to be discussed):
* Date
* Time
* Location
* Coordinates
* Description
* Title
* Associated organizations
* Attached photo / thumbnail

**Comment by sascha11110** [comment]
I think we should build all the stuff like revisions and translation management as generically as possible, so that we could add these features to all entitites. This becomes especially interesting when we want to expand our system with new entities or collaborate with other projects.

**Comment by sascha11110** [comment]
It should also be possible to create recurring events in the same view.

**Comment by timoludwig** [comment]
Closed via #224

**Comment by florianhofhammer** [comment]
Features still missing are addressed in other issues.
Therefore, this issue was closed, as the `feature/events` branch was merged into `develop`.
