### ISSUE TITLE
Check if current object belongs to selected region

### ISSUE THREAD

**Issue by jnugh** [Integreat/cms-django#322]
Right now there is no decorator or other measure to check if an object belongs to the currently selected region.

e.g. there is a POI (id: 42) for region 1, and there is a user in region 2 who is allowed to edit POIs, this user can now go to /region-slug-2/pois/language/42/edit and change the content of the POI that actually belongs to region 1.
This is probably also true for events and pages (I did not verify this yet).

**Comment by timoludwig** [comment]
I'm not aware of any of Django's inbuilt principles which could enforce this:

1. [Context Processors](https://docs.djangoproject.com/en/2.2/ref/templates/api/#playing-with-context-objects) can only inject variables into the template context
2. [Middlewares](https://docs.djangoproject.com/en/2.2/topics/http/middleware/) can only modify a request object in place
3. [Model Managers](https://docs.djangoproject.com/en/2.2/topics/db/managers/) do not have access to the current request

So, I see three options here:

1. We use one of these two statements every time we retrieve objects from the database:
    - `Page.objects.get(id=page_id, region=current_region)`
    - `current_region.pages.get(id=page_id)`

    In this case, we'll always have the risk of making mistakes in the future by using the current syntax  `Page.objects.get(id=id)` - maybe another CircleCI job can check our code base for insecure calls without a `region` keyword? Sounds like messy regex-magic...
2. We install the dependency [django-crequest](https://pypi.org/project/django-crequest/), a middleware which passes the current request to a global scope:
    ```
    class RegionPageManager(models.Manager):
        def get_queryset(self):
            current_region = Region.get_current_region(CrequestMiddleware.get_request())
            return super().get_queryset().filter(region=current_region)
    ```
    This manager can then only be used from within views and won't work on the command line etc.
    Also, the separation of models from the current request in Django was done on purpose, so this is definitely a suboptimal solution.
3. We install the dependency [django-scopes](https://pypi.org/project/django-scopes/) which does exactly what we want:
    ```
    from django_scopes import scope

    with scope(region=current_region):
        Page.objects.get(id=page_id)
    ```
    But this also comes which a few caveats, e.g. the default admin backend does not work anymore and testing gets more complicated in the future.

Does anybody have opinions on this?

**Comment by timoludwig** [comment]
In our call, we concluded that we favour solution 1 and do not want to interfere with the Django core too much. To minimize the risk of mistakes, we add a check to our CircleCI pipeline.
