### ISSUE TITLE
Improve documentation of gvz_api package

### ISSUE THREAD

**Issue by timoludwig** [Integreat/cms-django#338]
add docstrings to the gvz_api package.
```
"""[Summary]

:param [ParamName]: [ParamDescription], defaults to [DefaultParamVal]
:type [ParamName]: [ParamType](, optional)
...
:raises [ErrorType]: [ErrorDescription]
...
:return: [ReturnDescription]
:rtype: [ReturnType]
"""
```

**Comment by svenseeberg** [comment]
I guess I already added it for all GVZ API functions

**Comment by timoludwig** [comment]
Oh sorry, I missed that.
And I wasn't aware that sphinx also understands the format with the newline, in fact I think it is much cleaner with the newline :) I will adapt this format also for the other issues.
