### ISSUE TITLE
PN: sending

### ISSUE THREAD

**Issue by svenseeberg** [Integreat/cms-django#34]
Send push notification to target group. Automatically translate to other languages if wanted by user. We want to support globally set topics, for example default "news", "refugees", or "supporters". The old channel structure needs to be supported: `/topics/[BLOG_ID]-[LANG_CODE]-[TOPIC]`. For details, see https://github.com/Integreat/cms/wiki/Firebase-Notifications

Support saving draft messages.

**Comment by sascha11110** [comment]
It should also be possible to define a main language (this will be used if there is no translation for a language).

**Comment by svenseeberg** [comment]
![image](https://user-images.githubusercontent.com/15197000/57796562-c8b27500-7748-11e9-90d1-2c95c502371f.png)
