### ISSUE TITLE
Pages: export PDF

### ISSUE THREAD

**Issue by svenseeberg** [Integreat/cms-django#35]
Export selected list of pages into PDF. Option to include table of content. Cache created PDFs.

It is probably a good thing to use the export PDF API for this feature. This ensures, that apps and back end produce the same results.

If possible we can include customization features for regions. For example, the cities could include their logos into the header or footer. This is covered in #213

**Comment by maxammann** [comment]
I can recommend reportlabs: https://github.com/digitalfabrik/voucher-pdf-generator/blob/master/src/VoucherPrint.py

**Comment by timoludwig** [comment]
> I can recommend reportlabs: https://github.com/digitalfabrik/voucher-pdf-generator/blob/master/vpg/VoucherPrint.py

Yes, reportlab is also recommended by the official [Django documentation](https://docs.djangoproject.com/en/2.2/howto/outputting-pdf/). :+1:
