### ISSUE TITLE
Add ImprintPage model

### ISSUE THREAD

**Issue by timoludwig** [Integreat/cms-django#357]
Add an `Imprint` and `ImprintTranslation` model which should be similar to `Page` and `PageTranslation`.

**Comment by Thomas125** [comment]
I made a test by creating to test-models one "Oberklasse" and one "Unterklasse" where Unterklasse inherits from Oberklasse.
When I query all Oberklasse-instance I get all instances, no matter which class was chosen on creation.
(When I query all Unterklasse-instances I only get the instances which were explicity created as Unterklasse-Instances, of course)

So, to keep the behaviour that "Page.objects.all()" only returns the "content pages" (not the disclaimer page) we would need something like a "GeneralPage" which is inherited from Page. Analog thing with PageTranslation.


Under these circumstances I find it more sensible to create a DisclaimerTranslation-model with the attributes `region`, `language` and `text` with region and language as composite primary key (or as constraint unique_together).
To handle the feedback, we can add a flag `is_desclaimer_feedback` to the region-feedback-model, which defaults to `False`.

**Comment by Thomas125** [comment]
Does the disclaimer page and its translations have the same translation workflow like the normal pages? Do we also keep older versions?
So do we need the `attributes, currently_in_translation version, minor_edit`-attributes for a disclaimer page?

**Comment by timoludwig** [comment]
Oh sorry, it seems that I should have done better research before proposing this.

I found a few ways how to achieve the desired behaviour with a custom model manager, but this is kind of hacky and not worth the drawbacks I think.

So yes, probably it's best to define these as standalone classes... if we use an abstract base class for the content in the future, we can make our optimizations there.

**Comment by timoludwig** [comment]
One other option would be to define an `AbstractBasePage` which is the parent model of `Page` and `Disclaimer` and an `AbstractBasePageTranslation` which is the parent model of `PageTranslation` and `DisclaimerTranslation`.
Maybe, this can also be implemented together with #320 Refactor translation models.
