### ISSUE TITLE
Add gettext to system dependencies

### ISSUE THREAD

**Issue by thimmy687** [Integreat/cms-django#362]
By following the guide I got the messages below:

(.venv) thimmy687@DESKTOP-02QGADK:~/workspace/cms-django$ ./dev-tools/translate.sh
CommandError: Can't find msguniq. Make sure you have GNU gettext tools 0.15 or newer installed.
CommandError: Can't find msgfmt. Make sure you have GNU gettext tools 0.15 or newer installed.

![image](https://user-images.githubusercontent.com/7715216/79589554-e107de00-80d5-11ea-97eb-2d83b8735978.png)

**Comment by timoludwig** [comment]
Ok, I didn't know there is a distribution without gettext :sweat_smile: 
I'll add this dependency to the install script.
For you, the issue should be resolved after you installed gettext via your package manager.
