### ISSUE TITLE
Translation: import XLIFF

### ISSUE THREAD

**Issue by svenseeberg** [Integreat/cms-django#38]
Import translations for pages from XLIFF file. Importing should be handled similarly as manually editing a page. That means a new page version is created and potentially requires a review.

**Comment by svenseeberg** [comment]
I'll create a Python module that we can use in Django for managing all translation stuff.

**Comment by rasmus-storjohann-PG** [comment]
We use [Django parler](https://github.com/django-parler/django-parler) to manage multilingual content on the server. It's pretty easy to work with in terms of how to write the server logic. It imports/exports in PO/POT files, we haven't battle-tested that part yet, so I can't speak to how well it works.
