### ISSUE TITLE
Python3.7-dev is causing problems

### ISSUE THREAD

**Issue by ulliholtgrave** [Integreat/cms-django#380]
Even though the python3.7-dev is installed, the install.sh script stops and returns the following response:
![grafik](https://user-images.githubusercontent.com/15608678/80219570-f4b9c400-8642-11ea-9436-c13f3613d22d.png)

**Comment by thimmy687** [comment]
I have also this issue, I thought that was because I use the WSL on windows, but this seems not the issue.

Seems that the grep is buggy, maybe we can change the evaluation and replace grep

**Comment by timoludwig** [comment]
Ok, at first I wondered, but I'm the one who is buggy, not grep :rofl:
