### ISSUE TITLE
Short URL support

### ISSUE THREAD

**Issue by svenseeberg** [Integreat/cms-django#384]
We may want so share pages with shorter URLs. In some cases, page URLs are very long. Therefore we could use a URL shortening tool, akin to bit.ly (but more privacy friendly). We could either have an integrated app (`shorturl`) that maps URLs like `cms.integreat-app.de/s/TOKEN` to the original URL, or use a completely outsourced tool.

**Comment by stanislavkocan** [comment]
Hello, can you please assign it to me ? I will work on it. 

Is there any share functionality where you would like to include it ? Or how the user gets that short url ? Thank you.

**Comment by svenseeberg** [comment]
I'd suggest that we have a button in the Page edit form that copies the short URL to the clip board. Additionally, we could have a button for this in the page list.

**Comment by stanislavkocan** [comment]
Hello, I tried several methods (without using shortening tool aka bit.ly) but there are few problems. I found a plugin (https://pypi.org/project/short_url/) which takes integer and returns short unique string. The only integer which could be usable is page id, but there would be problems with translations, as they also have same page id. I also tried to encode url to integer, but the integer was very big, and the plugin I mentioned in this case would produce much longer string, which is not suitable for short url.

I plan to implement something like this, but please let me know, if you see there any potential problems which I did not realize: 

1) There would be button in Pages (next to View, Edit, Archive, Delete page) for each page called Copy link.
2) After click on that button for first time for some page, it would generate random short string (with library fe. shortuuid).
3) There would be new CharField in AbstractBasePageTranslation, which would store that short string or some default value in case random string was not generated yet for that page.
4) Copy link button would paste url with returned short string in right format (fe. app/s/dsjk5) to clipboard.
5) When user comes to link app/s/dsjk5, it would take dsjk5, filter the page and get absolute url of that page.
6) There would be redirect function, which would redict user to returned absolute url.

Let me know what you think.  Thanks.
