### ISSUE TITLE
Pages endpoint: skip pages if parent is not visible

### ISSUE THREAD

**Issue by svenseeberg** [Integreat/cms-django#386]
If a parent page in the page tree is in any state that makes it invisible in the API, we do not want the children to appear in the pages endpoint. This should allow for easy deactivating of "full chapters".

**Comment by timoludwig** [comment]
Just to wrap my head around this... this does only apply to the `archived` flag, not to the `draft`/`review`/`public`-status of the page translations, right?
I thought that, when a page is set as draft or in-review, the API should deliver the most recent public revision instead... and only when a page is archived, it is completely deactivated in the API... right?

**Comment by svenseeberg** [comment]
Yes, basically only to `archived`. But if there is no released version of the parent, i.e. there is only the current `draft` version, then children should not be shown as well.
