### ISSUE TITLE
Redirect user to their region

### ISSUE THREAD

**Issue by ulliholtgrave** [Integreat/cms-django#394]
So far user are redirected to the network admin panel even though they are not a superuser or staff. As they are assigned to a region, they should be redirected to the region dashboard instead.

**Comment by timoludwig** [comment]
I cannot reproduce this. We have already a redirect view which determines if the user is admin or not and region users are redirected to the region dashboard:

https://github.com/Integreat/cms-django/blob/8e026dc043a153b3ee3216901166bdd8ceaf2fa7/src/cms/views/dashboard/redirect_view.py#L24-L29
