### ISSUE TITLE
Convert test data to html

### ISSUE THREAD

**Issue by ulliholtgrave** [Integreat/cms-django#396]
![grafik](https://user-images.githubusercontent.com/15608678/82731827-ae22bc80-9d09-11ea-986a-27cd274f4e7e.png)
The publishing of a page changes the content. As you can see on the screenshot the api delivers the content created by the test_data in "rendered" HTML, but the updated content comes in plain HTML.

**Comment by timoludwig** [comment]
This is not a bug, but a feature :rofl: 

We want to have html-tags in the content, so it's good that tinymce inserts `<p>`-tags around paragraphs. So this is only a quality problem of the test data. Until now, it wasn't a problem that the initial test data did not contain valid html. But yes, in the future it would be better if we converted the content of the test data to html.
