### ISSUE TITLE
Admin: duplicate regions

### ISSUE THREAD

**Issue by svenseeberg** [Integreat/cms-django#43]
Duplicate a site with all its content except for users.

**Comment by timoludwig** [comment]
possible approach: https://stackoverflow.com/questions/32234986/duplicate-django-model-instance-and-all-foreign-keys-pointing-to-it

**Comment by timoludwig** [comment]
I assume that this does not include events, POIs, push notifications and feedback, right?
So instead of "all except users", maybe "duplicate region including languages, pages and media" would be more accurate...
