### ISSUE TITLE
Manual creation of Languages results in Bugsplash at page view.

### ISSUE THREAD

**Issue by ulliholtgrave** [Integreat/cms-django#434]
### Describe the Bug
If a system is set up manually without the test data. The manual language setup results in a error when opening the list view of the pages.
![grafik](https://user-images.githubusercontent.com/15608678/87561440-fc768b00-c6bc-11ea-8853-6207ba1d4b5b.png)

### Steps to Reproduce

1. Create Languages (Like German with code DE_de)
2. Create Region (Like Berlin)
3. Add Language Tree model like German -> English
4. Click on Pages and see error

### Expected Behavior
The usual list should be displayed. 

### Actual Behavior
Error message from Django.

### Additional Information
I guess this has something to do with manually setting the language code and this can't be matched by django.

**Comment by timoludwig** [comment]
This error exists, because the backend-languages have different language codes (`de-de`) than the content-languages in your setup (`DE_de`).

However, even if it is an unusual use case, we should catch those errors and make it possible to use the cms even if the backend languages are not a subset of the content languages.

**Comment by svenseeberg** [comment]
When going to the language tree, I see the following message:
```

Request Method: | GET
-- | --
http://localhost:8000/augsburg/language-tree/
2.2.14
TypeError
'NoneType' object is not iterable
/home/sven/Code/integreat-cms-django/.venv/lib64/python3.6/site-packages/mptt/templatetags/mptt_tags.py  in _render_node, line 257
/home/sven/Code/integreat-cms-django/.venv/bin/python3
3.6.10
['/home/sven/Code/integreat-cms-django/.venv/bin',  '/usr/lib/python36.zip',  '/usr/lib64/python3.6',  '/usr/lib64/python3.6/lib-dynload',  '/home/sven/Code/integreat-cms-django/.venv/lib64/python3.6/site-packages',  '/home/sven/Code/integreat-cms-django/src',  '/home/sven/Code/integreat-cms-django/.venv/lib/python3.6/site-packages']
Fri, 17 Jul 2020 11:31:45 +0000

```
I guess this is related? Outdated fixtures?

**Comment by timoludwig** [comment]
Strange. Unfortunately, this is not related, because I also get this error when the backend languages have the same language codes as the content languages. I opened a new issue (#436) and will have a look into it.
