### ISSUE TITLE
Admin: manage users

### ISSUE THREAD

**Issue by svenseeberg** [Integreat/cms-django#44]
Create, edit and delete users with e-mail, login, password, site access, role assignments.

Assign users to sites.

See also #45.

**Comment by sascha11110** [comment]
We also need a username besides the email address

**Comment by rasmus-storjohann-PG** [comment]
You'll get most or all of this for free from [cookiecutter](https://cookiecutter-django.readthedocs.io/en/latest/)

**Comment by timoludwig** [comment]
- add organization model with name and thumbnail/badge
- extend user model with:
  - many to many relation to sites (meaning all regions a user has access to or the favourite regions if the user is an administrator)
  - foreign key to organizations (so the organization's badge can be shown on every page a specific user created)
- make use of Django's permissions (check permissions when making changes to the database)

**Comment by Ponitac** [comment]
Possible Django extension for that case: https://django-guardian.readthedocs.io/en/stable/userguide/check.html
