### ISSUE TITLE
Rename points of interest

### ISSUE THREAD

**Issue by timoludwig** [Integreat/cms-django#492]
### Motivation

The term "points of interest" (POIs) is not recognized as locations on the map.

### Proposed Solution

Change the wording, e.g.
- English: "Locations on map"
- German: "Orte auf Karte"

**Comment by Yashs911** [comment]
Hey, @timoludwig I would like to work on this.

**Comment by Yashs911** [comment]
Can you please guide in which file I need to rename?

**Comment by timoludwig** [comment]
> Hey, @timoludwig I would like to work on this.

Nice, we really appreciate it!

> Can you please guide in which file I need to rename?

The string "Points of Interest" with "Locations on map" in following files:
- [src/cms/templates/_base.html](https://github.com/Integreat/cms-django/tree/develop/src/cms/templates/_base.html)
- [src/cms/templates/pois/poi_list.html](https://github.com/Integreat/cms-django/tree/develop/src/cms/templates/pois/poi_list.html)
- [src/cms/templates/pois/poi_list_archived.html](https://github.com/Integreat/cms-django/tree/develop/src/cms/templates/pois/poi_list_archived.html)

The string "POI" with "Locations on map" (only in strings, not in class names) in the following files:
- [src/cms/views/pois/poi_view.py](https://github.com/Integreat/cms-django/tree/develop/src/cms/views/pois/poi_view.py)
- [src/cms/views/pois/poi_actions.py](https://github.com/Integreat/cms-django/tree/develop/src/cms/views/pois/poi_actions.py)
- [src/cms/views/pois/poi_list_view.py](https://github.com/Integreat/cms-django/tree/develop/src/cms/views/pois/poi_list_view.py)

Please keep an eye on lower/upper case.
After that, execute `./dev-tools/translate.sh` to re-create the language file [src/cms/locale/de/LC_MESSAGES/django.po](https://github.com/Integreat/cms-django/tree/develop/src/cms/locale/de/LC_MESSAGES/django.po).
Then, insert the German translation "Orte auf Karte" in the related `msgstr` sections of the language file.

Feel free to ask any questions, if you feel uncomfortable with the German translations, you can also only change the English strings and we will add the rest. Thanks in advance!

**Comment by Yashs911** [comment]
@timoludwig I made all the changes but I could not run the ./dev-tools/install.sh command hence the ./dev-tools/translate.sh.
I am using windows (cmd prompt) could you please guide me which software I need to download so that I can run ./dev-tools/translate.sh command.
Thanks for your guidance.

**Comment by timoludwig** [comment]
I was able to install our CMS on Windows using the [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/). See [our documentation](https://integreat.github.io/cms-django/installation.html) for more information.

If you think this is too much work for this task, you can just push your changes and I will adjust the translations.

**Comment by Yashs911** [comment]
@timoludwig Okay for now I have created a pull request. I guess I need to shift to linux soon.
Thanks for helping me.

**Comment by timoludwig** [comment]
Cool, we'd really appreciate it if you wanted to contribute to our project in the future!

**Comment by Yashs911** [comment]
Hi, @timoludwig I tried creating a PR for some other issue for the same repo but when I click Pull Request I see both my new commit and my previous commit(this one). I am new to open source can you tell me what should I do?

**Comment by timoludwig** [comment]
The reason for this is that I combined your two commits from your develop branch into one commit before merging into our develop branch. Since git doesn't know that these commits are equivalent, it thinks that your two commits are still missing from our develop branch and wants to merge them if you open a new PR.

My suggestion is to work with local feature branches even on your own fork. So every time you work on a new issue, create a new branch and keep your develop branch exactly in sync with ours.

To fix the current state, you have two options:
- Delete and re-initialize your fork again or
- Remove your two commits from your develop branch and force-push:
```
git reset --hard HEAD~2
git push origin HEAD --force
```
After that, you should create a new [upstream remote](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/configuring-a-remote-for-a-fork) and then you can [sync your fork](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/syncing-a-fork) every time our develop branch gets updated.

**Comment by Yashs911** [comment]
@timoludwig Thanks a lot. In future if I make a separate branch to work then do I need to merge it or I can just push that feature branch and create a PR

**Comment by timoludwig** [comment]
> @timoludwig Do I need to merge it or I can just push that feature branch and create a PR

Please open your PR directly from your feature branch without merging it in your fork. Select `Integreat/cms-django/develop` as base and e.g. `Yashs911/cms-django/feature/xyz` as head.
