### ISSUE TITLE
Pages: New approach to control the arrangement of pages

### ISSUE THREAD

**Issue by sascha11110** [Integreat/cms-django#50]
Currently there are two ways to determine the arrangement of the pages:
1) Tree view: Drag & Drop
2) Detailed view: Determining the order and the parent page

In particular, defining the order is not satisfactory, as the numbers are always assigned at different intervals.

My suggestion:
- define the parent page via select field
- then drag & drop between the existing children's pages

Are there any better suggestions?

**Comment by timoludwig** [comment]
I like this approach!

**Comment by Schedulaar** [comment]
Do we only implement one of the two? I'd prefer if we had both a global drag-and-droppable tree view and the option you suggested in the detailed view

**Comment by timoludwig** [comment]
Yes, we provide both options. The drag & drop in the tree view is covered in this issue: #10.
Probably we can use the same drag & drop code snippets for both.

**Comment by svenseeberg** [comment]
I'm not totally convinced yet. This makes changing the full tree very tedious.

Is there a reason to not support moving pages to other parent pages via drag & drop?

**Comment by timoludwig** [comment]
@svenseeberg I think this is a misunderstanding... We DO want to support drag & drop in both the page tree view and the single page form.

**Comment by svenseeberg** [comment]
Thanks for clarifying.
