### ISSUE TITLE
Improve recurring event fields

### ISSUE THREAD

**Issue by timoludwig** [Integreat/cms-django#506]
### Motivation

In our survey, two problems with the event form for recurring events were expressed:
1. The participants did not understand the weekly recurrence
2. The participants did not know what "interval" means

### Proposed Solution

Change the behaviour of the event form:
1. [ ] The default recurring frequency should be weekly, not daily
2. [ ] The interval should be labelled differently, e.g. "Repeat every ... times"/"Jedes ...-te Mal wiederholen"

### Additional Context

![recurring_events](https://user-images.githubusercontent.com/16021269/94345498-91cfbd00-0026-11eb-82eb-4b32dfa0ff8c.png)

**Comment by mckinly** [comment]
Hi @timoludwig, I can work on this if you'd like.

**Comment by timoludwig** [comment]
> Hi @timoludwig, I can work on this if you'd like.

Amazing, thanks! Feel free to ask any questions if the issue description is unclear.

**Comment by mckinly** [comment]
I have a question, @timoludwig ...und zwar irgendwie wechselt die Sprache für mich nicht völlig. Die App funktioniert für mich lokal bzw. ich kann die localhost Webseite erreichen und einloggen als root usw. Vielleicht liegt es darum das ich in der USA bin? 

<img width="326" alt="Screen Shot 2020-10-05 at 9 57 51 AM" src="https://user-images.githubusercontent.com/7299514/95109984-9832f880-06fa-11eb-9b8f-98f09b4b217c.png">

**Comment by timoludwig** [comment]
@mckinly hmm that's weird, I haven't experienced this problem before. What's the output of `./dev-tools/translate.sh`? And what are your installed locales (`locale -a`)?

If we don't get this to work, you can also just change the layout of the English source code and I will add the German translation afterwards.

**Comment by mckinly** [comment]
@timoludwig gettext wasn't installed so after doing that it now works. Thanks! I will keep at it

**Comment by mckinly** [comment]
@timoludwig This is ready for review https://github.com/Integreat/cms-django/pull/520/
