### ISSUE TITLE
Changeable region meta information

### ISSUE THREAD

**Issue by svenseeberg** [Integreat/cms-django#523]
### Motivation
Currently, the (web) app shows the same meta information for each region (city). To improve description of search results, we may want individual info for each region.

### Proposed Solution
Add API property that contains an individual meta description for regions.

### Alternatives
None

### Additional Context
The app would need to implement this as well.

**Comment by timoludwig** [comment]
Duplicate of #402

**Comment by svenseeberg** [comment]
Duplicate of #522 and #402
