### ISSUE TITLE
Skip translation test in commit hooks while rebasing

### ISSUE THREAD

**Issue by svenseeberg** [Integreat/cms-django#536]
When rebasing branches, the commit hooks fire each time. However, the translation check uses git features that break while a rebase is going on. The rebase breaks with:
```
Not a git repository
To compare two paths outside a working tree:
usage: git diff [--no-index] <path> <path>
Your translation file is not up to date.
Please check if any strings need manual translation.
```
This could be used to check for an ongoing rebase and skip the tests: https://stackoverflow.com/questions/3921409/how-to-know-if-there-is-a-git-rebase-in-progress

**Comment by timoludwig** [comment]
I could not reproduce the issue. I tried different branches and different methods of rebasing, even with intentional mistakes in the translation file, but on my machine the hooks don't run during rebase, only during commit.
What does your `git --version` say? (for me it's `git version 2.28.0`)

**Comment by svenseeberg** [comment]
I am on git version 2.26.2. @melegiul what is your git version?

**Comment by melegiul** [comment]
my version is 2.17.1

**Comment by melegiul** [comment]
I just added the ppa of the git maintainers to my package sources and updated my git to version 2.29.2. This solved the problem, seems like they fixed the bug in the meanwhile.

**Comment by timoludwig** [comment]
Ok, thanks! This is possibly related to the following:

> "git rebase" happens to call some hooks meant for "checkout" and
   "commit" by this was not a designed behaviour than historical
   accident.  This has been documented.

– [Git 2.27.0 Release Notes](https://github.com/git/git/blob/master/Documentation/RelNotes/2.27.0.txt)

I'll add a note to our troubleshooting guide in the documentation.
