### ISSUE TITLE
Public PDF export API

### ISSUE THREAD

**Issue by svenseeberg** [Integreat/cms-django#554]
In addition to the "internal" PDF export functionality, we need to have a public version that implements https://github.com/Integreat/cms/wiki/REST-API-PDF

This is used by the PDF export button of the web app.

**Comment by timoludwig** [comment]
The option with `pdf?id={id}` is currently not used, so only `pdf` and `pdf?url={permalink}` is required.

**Comment by melegiul** [comment]
Is the api response expected to be in json format (i.e. Django JsonResponse)? If so can you tell the expected format, like the key values? I think in this case you want a key-value pair containing the link to the PDF document.

**Comment by timoludwig** [comment]
No, our API should directly return the pdf document, like e.g. here:
https://cms.integreat-app.de/augsburg/de/wp-json/ig-mpdf/v1/pdf
