### ISSUE TITLE
RSS-Feed for the Dashboard

### ISSUE THREAD

**Issue by ulliholtgrave** [Integreat/cms-django#566]
### Motivation
As we are supporting a RSS-Feed on the current wordpress, we should deliver the same feature within our release. It should show the last blog entries from our website.

### Proposed Solution
It should be kind of equal to the current widget:
![grafik](https://user-images.githubusercontent.com/15608678/97785143-8af71580-1ba3-11eb-8159-36da574c65c5.png)

**Comment by timoludwig** [comment]
Duplicate of #5
