### ISSUE TITLE
Modular design for generic functionalities

### ISSUE THREAD

**Issue by sascha11110** [Integreat/cms-django#65]
There are several generic functionalities that could be applied to different entities (pages, events, imprint, locations, ...) like:

- Translation management
- Revisions
- Automatic saving
- Entity based search
- Role management

Do we want to build these functionalities modular so that we can add them to different entities now and in the future? If so, how?

**Comment by svenseeberg** [comment]
In one of our last calls we decided to move functions that are used into modules that can be reused. See directory `backend/cms/views/utils/`
