### ISSUE TITLE
TinyMCE adjustments

### ISSUE THREAD

**Issue by sascha11110** [Integreat/cms-django#70]
Compared to the current editor, the following features are to be removed:
- "View" / "Ansicht"
- "abc"
- "File > new document" / "Datei > Neues Dokument"
- "Edit > Insert as text" / "Bearbeiten > Als Text einfügen"
- "Insert > Page break" / "Einfügen > Seitenumbruch"
- "Format > strike through, super-/subscript, code" / "Format > Durchgestrichen, Hochgestellt, Tiefgestellt, Code"

The Wordpress design of the editor should be retained.

Currently the menu as well as the icons are used. Should we unify this? Further suggestions for improvement?

**Comment by dkehne** [comment]
![rausgestrichen](https://user-images.githubusercontent.com/4182469/69418226-8f237d80-0d1a-11ea-8623-f836b99dcc2a.png)

New Buttons needed:
- Insert file/media file
- "No translate" button
- Add icons button (mail, location, telephone, light, world-wb)

What's not needed anymore:
- tab "File" is not needed any more.

Do we still support the feature that inserted media-links (e.g. youtube) are visually converted to a video player and images can be dragged & dropped from external pages?

**Comment by dkehne** [comment]
we just 3 header-types (and maybe not the biggest ones)

**Comment by dkehne** [comment]
- [ ] Remove tab "File"
- [ ] Remove button "align left"
- [ ] Remove button "align right"
- [ ] Remove button "justify text (Blocksatz)"

- [ ] Add button "Insert file/media file"
- [ ] Add button "No translate"
- [ ] Add button(s) to insert 5 icons, which are attached to this issue
- [ ] Add functionality to link button: when an email-address is marked, the link should be generated automatically with mailto:, when telephone number it shoudl add tel:, adding a website should add https://
- [ ] Add functionality to insert internal links (choose from a list or 'type to search'

**Comment by dkehne** [comment]
[icons-adress-phone-tipp.zip](https://github.com/Integreat/cms-django/files/3879228/icons-adress-phone-tipp.zip)

**Comment by dkehne** [comment]
[icon-set-6.zip](https://github.com/Integreat/cms-django/files/3879230/icon-set-6.zip)

**Comment by ulliholtgrave** [comment]
All requested features, except the automatic identification of tels and mails and the intern linking, have been solved. The last features has been added to the new issue #234 and set to additional features.
