### ISSUE TITLE
Pages: Display title of backend language for translations

### ISSUE THREAD

**Issue by svenseeberg** [Integreat/cms-django#82]
On translations, show the title of the main language. This is necessary when the admin is not speaking the specific language but needs to edit other settings.

**Comment by timoludwig** [comment]
I'm not sure if I fully understood this. At the moment, the content language can be switched when clicking on the language-flags. So if necessary, an admin can also look at the pages with arabic titles etc. Is this the desired behaviour, or should the page titles always be shown in the backend-language (currently only german and english are available)?

**Comment by svenseeberg** [comment]
Yes, showing the titles in the UI language is even better. In some cases it would helpful to have the English or German title when editing the Arabic page. This is mostly for supporting admins when they cannot read the characters of the language and need to navigate through the pages.
