### ISSUE TITLE
Translation: Status icons

### ISSUE THREAD

**Issue by svenseeberg** [Integreat/cms-django#83]
Available icons should be:

* [x] no translation exists
* [ ] translation outdated
* [x] translation up to date
* [ ] translation in progress

**Comment by svenseeberg** [comment]
See #60

**Comment by svenseeberg** [comment]
Yes, I guess we need another database field.

**Comment by timoludwig** [comment]
Oh sorry, I just overlooked the fact that we have the field `currently_in_translation` already in our model :sweat_smile:
