### ISSUE TITLE
Translation: Side by side view

### ISSUE THREAD

**Issue by svenseeberg** [Integreat/cms-django#85]
Users should be able to edit translations with the source language in a split view. Displaying the diff in the source language from the last translation is a big bonus.

The diff will show changes in the source language since the target language was changed. Minor edits in the target language must be ignored.

**Comment by svenseeberg** [comment]
@sascha11110 is this issue closed or should we leave it open until the editor is where we want it to be?

**Comment by timoludwig** [comment]
I think the basic feature was completed in  #137, so I will close this.
We can create a follow-up issue for additional requirements.
