### ISSUE TITLE
Translation coverage analytics

### ISSUE THREAD

**Issue by svenseeberg** [Integreat/cms-django#9]
Generate report of translation coverage. This must include:
* A list of all outdated translations

Optional:
* Chart of coverage percentage per language and day for the last month

**Comment by svenseeberg** [comment]
This is related to #4

**Comment by timoludwig** [comment]
I think this was closed by mistake.
This issue has nothing to do with #110 (besides the fact that the term "analytics" appears in both titles).

**Comment by timoludwig** [comment]
Two questions regarding this issue:
    1) Do we really need a list here? How is this list different than the regular page tree (which should get filters for translation status in the future anyway)?
    2) What is meant by "percentage per language and day for the last month"? Is it really necessary to track the translation coverage over time?

**Comment by timoludwig** [comment]
In consultation with @svenseeberg, we decided to drop the list requirement. Thus, this issue is already closed.
