### ISSUE TITLE
Admin: Add Region-Settings View

### ISSUE THREAD

**Issue by Ponitac** [Integreat/cms-django#93]
Give the page-admins the possibility to select the values of relevant settings.

**Comment by Ponitac** [comment]
Values should be divided into static Meta (Name) and Settings that can be changed

**Comment by timoludwig** [comment]
I think this refers to settings like "status of the region", "activate events", "activate push notifications", "activate statistics", right?
One thing to discuss here: Should all verwalter be able to change this, or only Integreat staff?

**Comment by timoludwig** [comment]
These settings can be changed in the region form already. Do we need a separate settings page? Otherwise this issue is solved already.

**Comment by timoludwig** [comment]
Together with @Ponitac I concluded to close this issue (see my last comment why).
